const VOCAB = [
  { id: 1, greek: "Ἀβραάμ", chapter: 4, frequency: 73, meaning: "Abraham" },
  { id: 2, greek: "ἄγγελος", chapter: 4, frequency: 175, meaning: "angel, messenger" },
  { id: 3, greek: "ἀμήν", chapter: 4, frequency: 129, meaning: "verily, truly, amen, so let it be" },
  { id: 4, greek: "ἄνθρωπος", chapter: 4, frequency: 550, meaning: "man, mankind, person, people, human being" },
  { id: 5, greek: "ἀπόστολος", chapter: 4, frequency: 80, meaning: "apostle, envoy, messenger" },
  { id: 6, greek: "Γαλιλαία", chapter: 4, frequency: 61, meaning: "Galilee" },
  { id: 7, greek: "γραφή", chapter: 4, frequency: 50, meaning: "writing, Scripture" },
  { id: 8, greek: "Δαυίδ", chapter: 4, frequency: 59, meaning: "David" },
  { id: 9, greek: "δόξα", chapter: 4, frequency: 166, meaning: "glory, majesty, fame" },
  { id: 10, greek: "ἐγώ", chapter: 4, frequency: 2666, meaning: "I" },
  { id: 11, greek: "ἔσχατος", chapter: 4, frequency: 52, meaning: "last" },
  { id: 12, greek: "ζωή", chapter: 4, frequency: 135, meaning: "life" },
  { id: 13, greek: "θεός", chapter: 4, frequency: 1317, meaning: "God, god" },
  { id: 14, greek: "καί", chapter: 4, frequency: 9153, meaning: "and, even, also, namely" },
  { id: 15, greek: "καρδία", chapter: 4, frequency: 156, meaning: "heart" },
  { id: 16, greek: "κόσμος", chapter: 4, frequency: 186, meaning: "world, universe, humankind" },
  { id: 17, greek: "λόγος", chapter: 4, frequency: 330, meaning: "word, Word, statement, message" },
  { id: 18, greek: "Παῦλος", chapter: 4, frequency: 158, meaning: "Paul" },
  { id: 19, greek: "Πέτρος", chapter: 4, frequency: 156, meaning: "Peter" },
  { id: 20, greek: "πνεῦμα", chapter: 4, frequency: 379, meaning: "spirit, Spirit, wind, breath, inner life" },
  { id: 21, greek: "προφήτης", chapter: 4, frequency: 144, meaning: "prophet" },
  { id: 22, greek: "φωνή", chapter: 4, frequency: 139, meaning: "sound, noise, voice" },
  { id: 23, greek: "Χριστός", chapter: 4, frequency: 529, meaning: "Christ, Messiah, Anointed One" },

  { id: 24, greek: "ἀγάπη", chapter: 6, frequency: 116, meaning: "love" },
  { id: 25, greek: "ἄλλος", chapter: 6, frequency: 155, meaning: "other, another" },
  { id: 26, greek: "αὐτός", chapter: 6, frequency: 5597, meaning: "he, she, it, him, her, itself, same" },
  { id: 27, greek: "βασιλεία", chapter: 6, frequency: 162, meaning: "kingdom" },
  { id: 28, greek: "δέ", chapter: 6, frequency: 2792, meaning: "but, and" },
  { id: 29, greek: "ἐν", chapter: 6, frequency: 2752, meaning: "in, on, among" },
  { id: 30, greek: "ἔργον", chapter: 6, frequency: 169, meaning: "work, deed, action" },
  { id: 31, greek: "καιρός", chapter: 6, frequency: 85, meaning: "appointed time, time, season" },
  { id: 32, greek: "νῦν", chapter: 6, frequency: 147, meaning: "now, present" },
  { id: 33, greek: "ὁ", chapter: 6, frequency: 19867, meaning: "the" },
  { id: 34, greek: "ὅτι", chapter: 6, frequency: 1296, meaning: "that, since, because" },
  { id: 35, greek: "οὐ", chapter: 6, frequency: 1623, meaning: "not" },
  { id: 36, greek: "ὥρα", chapter: 6, frequency: 106, meaning: "hour, occasion, moment" },

  { id: 37, greek: "ἁμαρτία", chapter: 7, frequency: 173, meaning: "sin" },
  { id: 38, greek: "ἀρχή", chapter: 7, frequency: 55, meaning: "beginning, ruler" },
  { id: 39, greek: "γάρ", chapter: 7, frequency: 1041, meaning: "for, then" },
  { id: 40, greek: "εἶπεν", chapter: 7, frequency: 708, meaning: "he said, she said, it said" },
  { id: 41, greek: "εἰς", chapter: 7, frequency: 1767, meaning: "into, in, among" },
  { id: 42, greek: "ἐξουσία", chapter: 7, frequency: 102, meaning: "authority, power" },
  { id: 43, greek: "εὐαγγέλιον", chapter: 7, frequency: 76, meaning: "good news, Gospel" },
  { id: 44, greek: "Ἰησοῦς", chapter: 7, frequency: 917, meaning: "Jesus, Joshua" },
  { id: 45, greek: "κύριος", chapter: 7, frequency: 717, meaning: "Lord, lord, master, sir" },
  { id: 46, greek: "μή", chapter: 7, frequency: 1042, meaning: "not, lest" },
  { id: 47, greek: "οὐρανός", chapter: 7, frequency: 273, meaning: "heaven, sky" },
  { id: 48, greek: "οὗτος", chapter: 7, frequency: 1387, meaning: "this, he, she, it, these, they" },
  { id: 49, greek: "σύ", chapter: 7, frequency: 2906, meaning: "you" },
  { id: 50, greek: "υἱός", chapter: 7, frequency: 377, meaning: "son, descendant" },
  { id: 51, greek: "ὥστε", chapter: 7, frequency: 83, meaning: "therefore, so that" },
    { id: 52, greek: "ἀλλά", chapter: 8, frequency: 638, meaning: "but, yet, except" },
  { id: 53, greek: "ἀπό", chapter: 8, frequency: 646, meaning: "from, away from" },
  { id: 54, greek: "διά", chapter: 8, frequency: 667, meaning: "through, on account of, because of" },
  { id: 55, greek: "εἰμί", chapter: 8, frequency: 2462, meaning: "I am, exist, live, am present" },
  { id: 56, greek: "ἐκ", chapter: 8, frequency: 915, meaning: "from, out of" },
  { id: 57, greek: "ἡμέρα", chapter: 8, frequency: 389, meaning: "day" },
  { id: 58, greek: "ἦν", chapter: 8, frequency: 315, meaning: "he was, she was, it was" },
  { id: 59, greek: "θάλασσα", chapter: 8, frequency: 91, meaning: "sea, lake" },
  { id: 60, greek: "θάνατος", chapter: 8, frequency: 120, meaning: "death" },
  { id: 61, greek: "ἵνα", chapter: 8, frequency: 663, meaning: "in order that, that" },
  { id: 62, greek: "Ἰωάννης", chapter: 8, frequency: 135, meaning: "John" },
  { id: 63, greek: "λέγω", chapter: 8, frequency: 2353, meaning: "I say, speak" },
  { id: 64, greek: "μετά", chapter: 8, frequency: 469, meaning: "with, after" },
  { id: 65, greek: "οἰκία", chapter: 8, frequency: 93, meaning: "house, home" },
  { id: 66, greek: "οἶκος", chapter: 8, frequency: 114, meaning: "house, home" },
  { id: 67, greek: "ὄχλος", chapter: 8, frequency: 175, meaning: "crowd, multitude" },
  { id: 68, greek: "παρά", chapter: 8, frequency: 194, meaning: "from, beside, in the presence of, alongside of" },
  { id: 69, greek: "παραβολή", chapter: 8, frequency: 50, meaning: "parable" },
  { id: 70, greek: "πρός", chapter: 8, frequency: 700, meaning: "to, towards, with" },
  { id: 71, greek: "ὑπό", chapter: 8, frequency: 220, meaning: "by, under, below" },

  { id: 72, greek: "ἀγαθός", chapter: 9, frequency: 102, meaning: "good, useful" },
  { id: 73, greek: "ἀγαπητός", chapter: 9, frequency: 61, meaning: "beloved" },
  { id: 74, greek: "αἰώνιος", chapter: 9, frequency: 71, meaning: "eternal" },
  { id: 75, greek: "ἀλλήλων", chapter: 9, frequency: 100, meaning: "one another" },
  { id: 76, greek: "ἀπεκρίθη", chapter: 9, frequency: 82, meaning: "he answered, she answered, it answered" },
  { id: 77, greek: "δοῦλος", chapter: 9, frequency: 126, meaning: "slave, servant" },
  { id: 78, greek: "ἐάν", chapter: 9, frequency: 350, meaning: "if, when" },
  { id: 79, greek: "ἐμός", chapter: 9, frequency: 76, meaning: "my, mine" },
  { id: 80, greek: "ἐντολή", chapter: 9, frequency: 67, meaning: "commandment" },
  { id: 81, greek: "καθώς", chapter: 9, frequency: 182, meaning: "as, even as" },
  { id: 82, greek: "κακός", chapter: 9, frequency: 50, meaning: "bad, evil" },
  { id: 83, greek: "μου", chapter: 9, frequency: 564, meaning: "my" },
  { id: 84, greek: "νεκρός", chapter: 9, frequency: 129, meaning: "dead, dead body, corpse" },
  { id: 85, greek: "πιστός", chapter: 9, frequency: 67, meaning: "faithful, believing" },
  { id: 86, greek: "πονηρός", chapter: 9, frequency: 78, meaning: "evil, bad" },
  { id: 87, greek: "πρῶτος", chapter: 9, frequency: 155, meaning: "first, earlier" },
  { id: 88, greek: "τρίτος", chapter: 9, frequency: 56, meaning: "third" },

  { id: 89, greek: "ἅγιος", chapter: 10, frequency: 233, meaning: "holy, saints" },
  { id: 90, greek: "εἰ", chapter: 10, frequency: 502, meaning: "if" },
  { id: 91, greek: "εἰ μή", chapter: 10, frequency: 0, meaning: "except, if not" },
  { id: 92, greek: "εἷς", chapter: 10, frequency: 345, meaning: "one" },
  { id: 93, greek: "ἤδη", chapter: 10, frequency: 62, meaning: "now, already" },
  { id: 94, greek: "ὄνομα", chapter: 10, frequency: 231, meaning: "name, reputation" },
  { id: 95, greek: "οὐδείς", chapter: 10, frequency: 227, meaning: "no one, none, nothing" },
  { id: 96, greek: "πᾶς", chapter: 10, frequency: 1243, meaning: "each, every, all" },
  { id: 97, greek: "περί", chapter: 10, frequency: 333, meaning: "concerning, about, around" },
  { id: 98, greek: "σάρξ", chapter: 10, frequency: 147, meaning: "flesh, body" },
  { id: 99, greek: "σύν", chapter: 10, frequency: 128, meaning: "with" },
  { id: 100, greek: "σῶμα", chapter: 10, frequency: 142, meaning: "body" },
  { id: 101, greek: "τέκνον", chapter: 10, frequency: 99, meaning: "child, descendant" },
  { id: 102, greek: "τίς", chapter: 10, frequency: 555, meaning: "who, what, which, why" },
  { id: 103, greek: "τις", chapter: 10, frequency: 534, meaning: "a certain one, anyone, someone, something" },

  { id: 104, greek: "ἀδελφός", chapter: 11, frequency: 343, meaning: "brother" },
  { id: 105, greek: "ἄν", chapter: 11, frequency: 166, meaning: "untranslatable, makes statement contingent" },
  { id: 106, greek: "ἀνήρ", chapter: 11, frequency: 216, meaning: "man, male, husband" },
  { id: 107, greek: "ἐκκλησία", chapter: 11, frequency: 114, meaning: "church, Church, assembly, congregation" },
  { id: 108, greek: "ἐλπίς", chapter: 11, frequency: 53, meaning: "hope, expectation" },
  { id: 109, greek: "ἔξω", chapter: 11, frequency: 63, meaning: "without, outside" },
  { id: 110, greek: "ἐπί", chapter: 11, frequency: 890, meaning: "on, over, when, on the basis of, at, to, against" },
  { id: 111, greek: "ἡμεῖς", chapter: 11, frequency: 864, meaning: "we" },
  { id: 112, greek: "θέλημα", chapter: 11, frequency: 62, meaning: "will, desire" },
  { id: 113, greek: "ἴδε", chapter: 11, frequency: 29, meaning: "see, behold" },
  { id: 114, greek: "ἰδού", chapter: 11, frequency: 200, meaning: "see, behold" },
  { id: 115, greek: "καλός", chapter: 11, frequency: 101, meaning: "beautiful, good" },
  { id: 116, greek: "μήτηρ", chapter: 11, frequency: 83, meaning: "mother" },
  { id: 117, greek: "οὐδέ", chapter: 11, frequency: 143, meaning: "and not, not even, neither, nor" },
  { id: 118, greek: "πατήρ", chapter: 11, frequency: 413, meaning: "father" },
  { id: 119, greek: "πίστις", chapter: 11, frequency: 243, meaning: "faith, belief, trust, faithfulness" },
  { id: 120, greek: "ὕδωρ", chapter: 11, frequency: 76, meaning: "water" },
  { id: 121, greek: "ὑμεῖς", chapter: 11, frequency: 1840, meaning: "you" },
  { id: 122, greek: "φῶς", chapter: 11, frequency: 73, meaning: "light" },
  { id: 123, greek: "χάρις", chapter: 11, frequency: 155, meaning: "grace, favor, kindness" },
  { id: 124, greek: "ὧδε", chapter: 11, frequency: 61, meaning: "here" },
,
  { id: 125, greek: "αἰών", chapter: 12, frequency: 122, meaning: "age, eternity" },
  { id: 126, greek: "διδάσκαλος", chapter: 12, frequency: 59, meaning: "teacher" },
  { id: 127, greek: "εὐθύς", chapter: 12, frequency: 59, meaning: "immediately" },
  { id: 128, greek: "ἕως", chapter: 12, frequency: 146, meaning: "until, as far as" },
  { id: 129, greek: "μαθητής", chapter: 12, frequency: 261, meaning: "disciple" },
  { id: 130, greek: "μέν", chapter: 12, frequency: 179, meaning: "on the one hand, indeed" },
  { id: 131, greek: "μηδείς", chapter: 12, frequency: 90, meaning: "no one, nothing" },
  { id: 132, greek: "μόνος", chapter: 12, frequency: 114, meaning: "alone, only" },
  { id: 133, greek: "ὅπως", chapter: 12, frequency: 53, meaning: "how, that, in order that" },
  { id: 134, greek: "ὅσος", chapter: 12, frequency: 110, meaning: "as great as, as many as" },
  { id: 135, greek: "οὖν", chapter: 12, frequency: 499, meaning: "therefore, then, accordingly" },
  { id: 136, greek: "ὀφθαλμός", chapter: 12, frequency: 100, meaning: "eye, sight" },
  { id: 137, greek: "πάλιν", chapter: 12, frequency: 141, meaning: "again" },
  { id: 138, greek: "πούς", chapter: 12, frequency: 93, meaning: "foot" },
  { id: 139, greek: "ὑπέρ", chapter: 12, frequency: 150, meaning: "in behalf of, above" },

  { id: 140, greek: "γυνή", chapter: 13, frequency: 215, meaning: "woman, wife" },
  { id: 141, greek: "δικαιοσύνη", chapter: 13, frequency: 92, meaning: "righteousness" },
  { id: 142, greek: "δώδεκα", chapter: 13, frequency: 75, meaning: "twelve" },
  { id: 143, greek: "ἑαυτοῦ", chapter: 13, frequency: 319, meaning: "of himself, of herself, of itself, of themselves" },
  { id: 144, greek: "ἐκεῖνος", chapter: 13, frequency: 265, meaning: "that, those" },
  { id: 145, greek: "ἤ", chapter: 13, frequency: 343, meaning: "or, either, than" },
  { id: 146, greek: "κἀγώ", chapter: 13, frequency: 84, meaning: "and I, but I" },
  { id: 147, greek: "μακάριος", chapter: 13, frequency: 50, meaning: "blessed, happy" },
  { id: 148, greek: "μέγας", chapter: 13, frequency: 243, meaning: "large, great" },
  { id: 149, greek: "πόλις", chapter: 13, frequency: 162, meaning: "city" },
  { id: 150, greek: "πολύς", chapter: 13, frequency: 416, meaning: "much, many, often" },
  { id: 151, greek: "πῶς", chapter: 13, frequency: 103, meaning: "how" },
  { id: 152, greek: "σημεῖον", chapter: 13, frequency: 77, meaning: "sign, miracle" },

  { id: 153, greek: "ἀλήθεια", chapter: 14, frequency: 109, meaning: "truth" },
  { id: 154, greek: "εἰρήνη", chapter: 14, frequency: 92, meaning: "peace" },
  { id: 155, greek: "ἐνώπιον", chapter: 14, frequency: 94, meaning: "before" },
  { id: 156, greek: "ἐπαγγελία", chapter: 14, frequency: 52, meaning: "promise" },
  { id: 157, greek: "ἑπτά", chapter: 14, frequency: 88, meaning: "seven" },
  { id: 158, greek: "θρόνος", chapter: 14, frequency: 62, meaning: "throne" },
  { id: 159, greek: "Ἰερουσαλήμ", chapter: 14, frequency: 77, meaning: "Jerusalem" },
  { id: 160, greek: "κατά", chapter: 14, frequency: 473, meaning: "against, according to" },
  { id: 161, greek: "κεφαλή", chapter: 14, frequency: 75, meaning: "head" },
  { id: 162, greek: "ὁδός", chapter: 14, frequency: 101, meaning: "way, road, journey, conduct" },
  { id: 163, greek: "ὅς", chapter: 14, frequency: 1407, meaning: "who, whom, that, which" },
  { id: 164, greek: "ὅτε", chapter: 14, frequency: 103, meaning: "when" },
  { id: 165, greek: "οὕτως", chapter: 14, frequency: 208, meaning: "thus, so, in this manner" },
  { id: 166, greek: "πλοῖον", chapter: 14, frequency: 68, meaning: "ship, boat" },
  { id: 167, greek: "ῥῆμα", chapter: 14, frequency: 68, meaning: "word, saying" },
  { id: 168, greek: "τε", chapter: 14, frequency: 215, meaning: "and, so" },
  { id: 169, greek: "χείρ", chapter: 14, frequency: 177, meaning: "hand, arm, finger" },
  { id: 170, greek: "ψυχή", chapter: 14, frequency: 103, meaning: "soul, life, self" },
,
  { id: 171, greek: "ἀκούω", chapter: 16, frequency: 428, meaning: "I hear, learn, obey, understand" },
  { id: 172, greek: "βλέπω", chapter: 16, frequency: 133, meaning: "I see, look at" },
  { id: 173, greek: "ἔχω", chapter: 16, frequency: 708, meaning: "I have, hold, I am" },
  { id: 174, greek: "λύω", chapter: 16, frequency: 42, meaning: "I loose, set free, destroy" },
  { id: 175, greek: "νόμος", chapter: 16, frequency: 194, meaning: "law, principle" },
  { id: 176, greek: "ὅπου", chapter: 16, frequency: 82, meaning: "where" },
  { id: 177, greek: "πιστεύω", chapter: 16, frequency: 241, meaning: "I believe, have faith, trust" },
  { id: 178, greek: "πρόσωπον", chapter: 16, frequency: 76, meaning: "face, appearance" },
  { id: 179, greek: "τότε", chapter: 16, frequency: 160, meaning: "then, thereafter" },
  { id: 180, greek: "τυφλός", chapter: 16, frequency: 50, meaning: "blind" },
  { id: 181, greek: "χαρά", chapter: 16, frequency: 59, meaning: "joy, delight" },

  { id: 182, greek: "ἀγαπάω", chapter: 17, frequency: 143, meaning: "I love, cherish" },
  { id: 183, greek: "δαιμόνιον", chapter: 17, frequency: 63, meaning: "demon" },
  { id: 184, greek: "ζητέω", chapter: 17, frequency: 117, meaning: "I seek, desire, try to obtain" },
  { id: 185, greek: "καλέω", chapter: 17, frequency: 148, meaning: "I call, name, invite" },
  { id: 186, greek: "λαλέω", chapter: 17, frequency: 296, meaning: "I speak, say" },
  { id: 187, greek: "οἶδα", chapter: 17, frequency: 318, meaning: "I know, understand" },
  { id: 188, greek: "ὅταν", chapter: 17, frequency: 123, meaning: "whenever" },
  { id: 189, greek: "πλείων", chapter: 17, frequency: 55, meaning: "larger, more" },
  { id: 190, greek: "πληρόω", chapter: 17, frequency: 86, meaning: "I fill, complete, fulfill" },
  { id: 191, greek: "ποιέω", chapter: 17, frequency: 568, meaning: "I do, make" },
  { id: 192, greek: "τηρέω", chapter: 17, frequency: 70, meaning: "I keep, guard, observe" },

  { id: 193, greek: "ἀποκρίνομαι", chapter: 18, frequency: 231, meaning: "I answer" },
  { id: 194, greek: "δεῖ", chapter: 18, frequency: 101, meaning: "it is necessary" },
  { id: 195, greek: "δύναμαι", chapter: 18, frequency: 210, meaning: "I am able, am powerful" },
  { id: 196, greek: "ἔρχομαι", chapter: 18, frequency: 632, meaning: "I come, go" },
  { id: 197, greek: "νύξ", chapter: 18, frequency: 61, meaning: "night" },
  { id: 198, greek: "ὅστις", chapter: 18, frequency: 144, meaning: "whoever, whichever, whatever" },
  { id: 199, greek: "πορεύομαι", chapter: 18, frequency: 153, meaning: "I go, proceed, live" },
  { id: 200, greek: "συνάγω", chapter: 18, frequency: 59, meaning: "I gather together, invite" },
  { id: 201, greek: "τόπος", chapter: 18, frequency: 94, meaning: "place, location" },
  { id: 202, greek: "ὡς", chapter: 18, frequency: 504, meaning: "as, like, when, that, how, about" },

  { id: 203, greek: "βασιλεύς", chapter: 19, frequency: 115, meaning: "king" },
  { id: 204, greek: "γεννάω", chapter: 19, frequency: 97, meaning: "I beget, give birth to, produce" },
  { id: 205, greek: "ζάω", chapter: 19, frequency: 140, meaning: "I live" },
  { id: 206, greek: "Ἰουδαία", chapter: 19, frequency: 44, meaning: "Judea" },
  { id: 207, greek: "Ἰουδαῖος", chapter: 19, frequency: 194, meaning: "Jewish, a Jew" },
  { id: 208, greek: "Ἰσραήλ", chapter: 19, frequency: 68, meaning: "Israel" },
  { id: 209, greek: "καρπός", chapter: 19, frequency: 66, meaning: "fruit, result, crop" },
  { id: 210, greek: "μείζων", chapter: 19, frequency: 48, meaning: "greater" },
  { id: 211, greek: "ὅλος", chapter: 19, frequency: 109, meaning: "whole, complete, entirely" },
  { id: 212, greek: "προσκυνέω", chapter: 19, frequency: 60, meaning: "I worship" },
,
  { id: 213, greek: "αἴρω", chapter: 20, frequency: 101, meaning: "I raise, take up, take away" },
  { id: 214, greek: "ἀποκτείνω", chapter: 20, frequency: 74, meaning: "I kill" },
  { id: 215, greek: "ἀποστέλλω", chapter: 20, frequency: 132, meaning: "I send, send away" },
  { id: 216, greek: "βαπτίζω", chapter: 20, frequency: 77, meaning: "I baptize" },
  { id: 217, greek: "γινώσκω", chapter: 20, frequency: 222, meaning: "I know, come to know, realize, learn" },
  { id: 218, greek: "γλῶσσα", chapter: 20, frequency: 50, meaning: "tongue, language" },
  { id: 219, greek: "ἐγείρω", chapter: 20, frequency: 144, meaning: "I raise up, wake" },
  { id: 220, greek: "ἐκβάλλω", chapter: 20, frequency: 81, meaning: "I cast out, send out" },
  { id: 221, greek: "ἐκεῖ", chapter: 20, frequency: 105, meaning: "there, in that place" },
  { id: 222, greek: "κρίνω", chapter: 20, frequency: 114, meaning: "I judge, decide, prefer" },
  { id: 223, greek: "λαός", chapter: 20, frequency: 142, meaning: "people, crowd" },
  { id: 224, greek: "μένω", chapter: 20, frequency: 118, meaning: "I remain, live" },
  { id: 225, greek: "ὁράω", chapter: 20, frequency: 454, meaning: "I see, notice, experience" },
  { id: 226, greek: "σοφία", chapter: 20, frequency: 51, meaning: "wisdom" },
  { id: 227, greek: "στόμα", chapter: 20, frequency: 78, meaning: "mouth" },
  { id: 228, greek: "σῴζω", chapter: 20, frequency: 106, meaning: "I save, deliver, rescue" },

  { id: 229, greek: "ἀκολουθέω", chapter: 21, frequency: 90, meaning: "I follow, accompany" },
  { id: 230, greek: "διδάσκω", chapter: 21, frequency: 97, meaning: "I teach" },
  { id: 231, greek: "ἐπερωτάω", chapter: 21, frequency: 56, meaning: "I ask, question, demand" },
  { id: 232, greek: "ἐρωτάω", chapter: 21, frequency: 63, meaning: "I ask, request, entreat" },
  { id: 233, greek: "θέλω", chapter: 21, frequency: 208, meaning: "I will, wish, desire, enjoy" },
  { id: 234, greek: "περιπατέω", chapter: 21, frequency: 95, meaning: "I walk, live" },
  { id: 235, greek: "συναγωγή", chapter: 21, frequency: 56, meaning: "synagogue, meeting" },
  { id: 236, greek: "Φαρισαῖος", chapter: 21, frequency: 98, meaning: "Pharisee" },
  { id: 237, greek: "χρόνος", chapter: 21, frequency: 54, meaning: "time" },

  { id: 238, greek: "ἀποθνῄσκω", chapter: 22, frequency: 112, meaning: "I die" },
  { id: 239, greek: "ἄρτος", chapter: 22, frequency: 97, meaning: "bread, food" },
  { id: 240, greek: "βάλλω", chapter: 22, frequency: 122, meaning: "I throw, put" },
  { id: 241, greek: "γῆ", chapter: 22, frequency: 250, meaning: "earth, land, region, humanity" },
  { id: 242, greek: "γίνομαι", chapter: 22, frequency: 669, meaning: "I become, happen, exist, am born" },
  { id: 243, greek: "εἰσέρχομαι", chapter: 22, frequency: 194, meaning: "I enter, go in" },
  { id: 244, greek: "ἐξέρχομαι", chapter: 22, frequency: 218, meaning: "I go out, come out" },
  { id: 245, greek: "ἔτι", chapter: 22, frequency: 93, meaning: "still, yet, even" },
  { id: 246, greek: "εὑρίσκω", chapter: 22, frequency: 176, meaning: "I find" },
  { id: 247, greek: "λαμβάνω", chapter: 22, frequency: 258, meaning: "I take, receive" },
  { id: 248, greek: "οὔτε", chapter: 22, frequency: 87, meaning: "and not, neither, nor" },
  { id: 249, greek: "προσέρχομαι", chapter: 22, frequency: 86, meaning: "I come to" },
  { id: 250, greek: "προσεύχομαι", chapter: 22, frequency: 85, meaning: "I pray" },
  { id: 251, greek: "πῦρ", chapter: 22, frequency: 71, meaning: "fire" },

  { id: 252, greek: "ἀπέρχομαι", chapter: 23, frequency: 117, meaning: "I depart, go away" },
  { id: 253, greek: "ἄρχω", chapter: 23, frequency: 86, meaning: "I rule, I begin" },
  { id: 254, greek: "γράφω", chapter: 23, frequency: 191, meaning: "I write" },
  { id: 255, greek: "διό", chapter: 23, frequency: 53, meaning: "therefore, for this reason" },
  { id: 256, greek: "δοξάζω", chapter: 23, frequency: 61, meaning: "I glorify, praise, honor" },
  { id: 257, greek: "δύναμις", chapter: 23, frequency: 119, meaning: "power, miracle" },
  { id: 258, greek: "κηρύσσω", chapter: 23, frequency: 61, meaning: "I proclaim, preach" },
  { id: 259, greek: "πίνω", chapter: 23, frequency: 73, meaning: "I drink" },
  ,
  { id: 260, greek: "ἄγω", chapter: 24, frequency: 67, meaning: "I lead, bring, arrest" },
  { id: 261, greek: "αἷμα", chapter: 24, frequency: 97, meaning: "blood" },
  { id: 262, greek: "ἕκαστος", chapter: 24, frequency: 82, meaning: "each, every" },
  { id: 263, greek: "ἱμάτιον", chapter: 24, frequency: 60, meaning: "garment" },
  { id: 264, greek: "ὄρος", chapter: 24, frequency: 63, meaning: "mountain, hill" },
  { id: 265, greek: "ὑπάγω", chapter: 24, frequency: 79, meaning: "I depart" },
  { id: 266, greek: "φοβέομαι", chapter: 24, frequency: 95, meaning: "I fear" },
  { id: 267, greek: "χαίρω", chapter: 24, frequency: 74, meaning: "I rejoice" },

  { id: 268, greek: "αἰτέω", chapter: 25, frequency: 70, meaning: "I ask, demand" },
  { id: 269, greek: "μᾶλλον", chapter: 25, frequency: 81, meaning: "more, rather" },
  { id: 270, greek: "μαρτυρέω", chapter: 25, frequency: 76, meaning: "I bear witness, testify" },

  { id: 271, greek: "ἀναβαίνω", chapter: 27, frequency: 82, meaning: "I go up, come up" },
  { id: 272, greek: "ἀρχιερεύς", chapter: 27, frequency: 122, meaning: "chief priest, high priest" },
  { id: 273, greek: "δεξιός", chapter: 27, frequency: 54, meaning: "right" },
  { id: 274, greek: "δύο", chapter: 27, frequency: 135, meaning: "two" },
  { id: 275, greek: "ἕτερος", chapter: 27, frequency: 98, meaning: "other, another, different" },
  { id: 276, greek: "εὐαγγελίζω", chapter: 27, frequency: 54, meaning: "I preach good news" },
  { id: 277, greek: "θεωρέω", chapter: 27, frequency: 58, meaning: "I look at, behold" },
  { id: 278, greek: "Ἱεροσόλυμα", chapter: 27, frequency: 62, meaning: "Jerusalem" },
  { id: 279, greek: "κάθημαι", chapter: 27, frequency: 91, meaning: "I sit, live" },
  { id: 280, greek: "καταβαίνω", chapter: 27, frequency: 81, meaning: "I go down, come down" },
  { id: 281, greek: "οὗ", chapter: 27, frequency: 24, meaning: "where" },
  { id: 282, greek: "παρακαλέω", chapter: 27, frequency: 109, meaning: "I call, urge, comfort" },
  { id: 283, greek: "πείθω", chapter: 27, frequency: 52, meaning: "I persuade" },
  { id: 284, greek: "τρεῖς", chapter: 27, frequency: 68, meaning: "three" },

  { id: 285, greek: "ἀσπάζομαι", chapter: 28, frequency: 59, meaning: "I greet" },
  { id: 286, greek: "γραμματεύς", chapter: 28, frequency: 63, meaning: "scribe" },
  { id: 287, greek: "ἔφη", chapter: 28, frequency: 43, meaning: "he said, was saying" },
  { id: 288, greek: "ἱερόν", chapter: 28, frequency: 72, meaning: "temple" },
  { id: 289, greek: "κράζω", chapter: 28, frequency: 55, meaning: "I cry out" },
  { id: 290, greek: "οὐχί", chapter: 28, frequency: 54, meaning: "not" },
  { id: 291, greek: "παιδίον", chapter: 28, frequency: 52, meaning: "child, infant" },
  { id: 292, greek: "σπείρω", chapter: 28, frequency: 52, meaning: "I sow" },

  { id: 293, greek: "δέχομαι", chapter: 29, frequency: 56, meaning: "I receive" },
  { id: 294, greek: "δοκέω", chapter: 29, frequency: 62, meaning: "I think, seem" },
  { id: 295, greek: "ἐσθίω", chapter: 29, frequency: 158, meaning: "I eat" },
  { id: 296, greek: "πέμπω", chapter: 29, frequency: 79, meaning: "I send" },
  { id: 297, greek: "φέρω", chapter: 29, frequency: 66, meaning: "I carry, bear" },
,
  { id: 298, greek: "μηδέ", chapter: 30, frequency: 56, meaning: "but not, nor, not even" },
  { id: 299, greek: "πρεσβύτερος", chapter: 30, frequency: 66, meaning: "elder" },

  { id: 300, greek: "λίθος", chapter: 31, frequency: 59, meaning: "stone" },
  { id: 301, greek: "τοιοῦτος", chapter: 31, frequency: 57, meaning: "such, of such a kind" },

  { id: 302, greek: "δίκαιος", chapter: 32, frequency: 79, meaning: "righteous, just" },
  { id: 303, greek: "μέλλω", chapter: 32, frequency: 109, meaning: "I am about to" },

  { id: 304, greek: "ἀπόλλυμι", chapter: 33, frequency: 90, meaning: "I destroy, perish" },
  { id: 305, greek: "ἀπολύω", chapter: 33, frequency: 66, meaning: "I release" },
  { id: 306, greek: "εἴτε", chapter: 33, frequency: 65, meaning: "if, whether" },

  { id: 307, greek: "δίδωμι", chapter: 34, frequency: 415, meaning: "I give" },
  { id: 308, greek: "ἔθνος", chapter: 34, frequency: 162, meaning: "nation, Gentiles" },
  { id: 309, greek: "λοιπός", chapter: 34, frequency: 55, meaning: "remaining, rest" },
  { id: 310, greek: "Μωϋσῆς", chapter: 34, frequency: 80, meaning: "Moses" },
  { id: 311, greek: "παραδίδωμι", chapter: 34, frequency: 119, meaning: "I hand over, betray" },
  { id: 312, greek: "πίπτω", chapter: 34, frequency: 90, meaning: "I fall" },
  { id: 313, greek: "ὑπάρχω", chapter: 34, frequency: 60, meaning: "I exist" },

  { id: 314, greek: "ἀνίστημι", chapter: 35, frequency: 108, meaning: "I rise, raise" },
  { id: 315, greek: "ἀνοίγω", chapter: 35, frequency: 77, meaning: "I open" },
  { id: 316, greek: "ἀφίημι", chapter: 35, frequency: 143, meaning: "I forgive, leave, permit" },
  { id: 317, greek: "δείκνυμι", chapter: 35, frequency: 30, meaning: "I show" },
  { id: 318, greek: "ἴδιος", chapter: 35, frequency: 114, meaning: "one’s own" },
  { id: 319, greek: "ἵστημι", chapter: 35, frequency: 154, meaning: "I stand, cause to stand" },
  { id: 320, greek: "μέσος", chapter: 35, frequency: 58, meaning: "middle, midst" },
  { id: 321, greek: "τίθημι", chapter: 35, frequency: 100, meaning: "I put, place" },
  { id: 322, greek: "φημί", chapter: 35, frequency: 66, meaning: "I say" }
];

